### ISSUE TITLE
[evol] Classer les MT par ordre d'ajout décroissant, pour savoir lesquelles ajouter

### ISSUE THREAD

**Issue by pfilippi** [Nina-fm/nina.fm-faceb#3]

**Comment by fugudesign** [comment]
C'est déjà le cas en fait, après comme il n'y avait pas de date d'ajout dans les anciennes données, l'import à fait dans l'ordre de ce qu'il trouvait.
Mais au fur et à mesure que tu ajouteras des MT elles devraient normalement apparaitre tout en haut de la liste par défaut.

**Comment by pfilippi** [comment]
okei!
